# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Upload Python Package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'  # Ensures you get all history for all branches and tags
        token: ${{ secrets.GENERAL_ACCESS_TOKEN }}  # Allows pushing back to the repository

    # Check if the last commit was made by an automated process to prevent recursive triggering
    - name: Check commit message
      id: check_commit
      run: |
        commit_message=$(git log -1 --pretty=%B)
        echo "Commit message: $commit_message"
        if [[ $commit_message == *"Bump version"* ]]; then
          echo "Automated commit detected. Setting skip flag to true."
          echo "skip=true" >> $GITHUB_ENV
        fi

    - name: Set up Python
      if: env.skip != 'true'
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      if: env.skip != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine bump2version

    - name: Bump version and commit changes
      if: env.skip != 'true'
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        bump2version patch  # Or minor or major, depending on your strategy
      env:
        GITHUB_TOKEN: ${{ secrets.GENERAL_ACCESS_TOKEN  }}

    - name: Push changes
      if: env.skip != 'true'
      run: git push --follow-tags
      env:
        GITHUB_TOKEN: ${{ secrets.GENERAL_ACCESS_TOKEN  }}

    - name: Build and publish
      if: env.skip != 'true'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
